-- Run once in the Supabase SQL Editor for this project.
-- Only the server-side service_role key can access these objects through the Data API.

create table if not exists public.chats (
    chat_id bigint primary key,
    title text not null,
    chat_type text not null,
    membership text,
    last_seen_utc timestamptz not null
);

create table if not exists public.messages (
    chat_id bigint not null references public.chats(chat_id),
    message_id bigint not null,
    sent_utc timestamptz not null,
    edited_utc timestamptz,
    author_id bigint,
    author_name text,
    text text,
    content_type text not null,
    reply_to_message_id bigint,
    thread_id bigint,
    source text not null default 'bot',
    source_file text,
    primary key (chat_id, message_id)
);

create index if not exists messages_by_time
    on public.messages(chat_id, sent_utc desc);

create table if not exists public.scheduled_actions (
    id bigint generated by default as identity primary key,
    chat_id bigint not null references public.chats(chat_id),
    action_type text not null check (action_type in ('message', 'poll')),
    payload jsonb not null,
    scheduled_for timestamptz not null,
    repeat_interval_minutes integer check (repeat_interval_minutes is null or repeat_interval_minutes > 0),
    status text not null default 'pending' check (status in ('pending', 'processing', 'sent', 'failed', 'cancelled')),
    attempts integer not null default 0,
    telegram_message_id bigint,
    last_error text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    sent_at timestamptz
);

alter table public.scheduled_actions
    add column if not exists dedupe_key text;

create unique index if not exists scheduled_actions_dedupe
    on public.scheduled_actions(dedupe_key);

create table if not exists public.daily_polls (
    poll_id text primary key,
    chat_id bigint not null references public.chats(chat_id),
    thread_id bigint not null,
    work_date date not null,
    telegram_message_id bigint not null,
    created_at timestamptz not null default now(),
    unique (chat_id, work_date)
);

create table if not exists public.daily_poll_answers (
    poll_id text not null references public.daily_polls(poll_id) on delete cascade,
    user_id bigint not null,
    user_name text,
    active boolean not null,
    updated_at timestamptz not null default now(),
    primary key (poll_id, user_id)
);

create index if not exists scheduled_actions_due
    on public.scheduled_actions(status, scheduled_for);

alter table public.chats enable row level security;
alter table public.messages enable row level security;
alter table public.scheduled_actions enable row level security;
alter table public.daily_polls enable row level security;
alter table public.daily_poll_answers enable row level security;
revoke all on public.chats, public.messages, public.scheduled_actions, public.daily_polls, public.daily_poll_answers from public, anon, authenticated;
grant select, insert, update on public.chats, public.messages, public.scheduled_actions, public.daily_polls, public.daily_poll_answers to service_role;
grant usage, select on sequence public.scheduled_actions_id_seq to service_role;

create or replace function public.insights_ingest_update(
    p_update jsonb,
    p_allowed_ids bigint[]
) returns boolean
language plpgsql
security invoker
set search_path = ''
as $$
declare
    v_message jsonb;
    v_member jsonb;
    v_chat jsonb;
    v_sender jsonb;
    v_chat_id bigint;
    v_name text;
    v_kind text;
begin
    v_message := coalesce(p_update->'message', p_update->'edited_message');
    v_member := p_update->'my_chat_member';
    v_chat := coalesce(v_message->'chat', v_member->'chat');
    if v_chat is null or v_chat->>'type' not in ('group', 'supergroup') then
        return false;
    end if;
    v_chat_id := (v_chat->>'id')::bigint;
    if v_chat_id is null then
        return false;
    end if;

    insert into public.chats(chat_id, title, chat_type, membership, last_seen_utc)
    values (
        v_chat_id,
        coalesce(nullif(v_chat->>'title', ''), v_chat_id::text),
        v_chat->>'type',
        v_member->'new_chat_member'->>'status',
        now()
    )
    on conflict (chat_id) do update set
        title = excluded.title,
        chat_type = excluded.chat_type,
        membership = coalesce(excluded.membership, public.chats.membership),
        last_seen_utc = excluded.last_seen_utc;

    if not (v_chat_id = any(p_allowed_ids)) then
        return false;
    end if;

    if v_message is null then
        return true;
    end if;

    v_sender := coalesce(v_message->'from', v_message->'sender_chat', '{}'::jsonb);
    v_name := nullif(trim(concat_ws(' ', v_sender->>'first_name', v_sender->>'last_name')), '');
    v_name := coalesce(v_name, v_sender->>'title', v_sender->>'username');
    v_kind := case
        when v_message ? 'photo' then 'photo'
        when v_message ? 'video' then 'video'
        when v_message ? 'document' then 'document'
        when v_message ? 'audio' then 'audio'
        when v_message ? 'voice' then 'voice'
        when v_message ? 'animation' then 'animation'
        when v_message ? 'sticker' then 'sticker'
        when v_message ? 'poll' then 'poll'
        when v_message ? 'location' then 'location'
        when v_message ? 'contact' then 'contact'
        when v_message ? 'text' then 'text'
        else 'other'
    end;

    insert into public.messages(
        chat_id, message_id, sent_utc, edited_utc, author_id,
        author_name, text, content_type, reply_to_message_id,
        thread_id, source
    ) values (
        v_chat_id,
        (v_message->>'message_id')::bigint,
        to_timestamp((v_message->>'date')::double precision),
        case when v_message ? 'edit_date'
            then to_timestamp((v_message->>'edit_date')::double precision)
            else null end,
        nullif(v_sender->>'id', '')::bigint,
        v_name,
        coalesce(v_message->>'text', v_message->>'caption'),
        v_kind,
        nullif(v_message->'reply_to_message'->>'message_id', '')::bigint,
        nullif(v_message->>'message_thread_id', '')::bigint,
        'bot'
    )
    on conflict (chat_id, message_id) do update set
        edited_utc = excluded.edited_utc,
        author_id = excluded.author_id,
        author_name = excluded.author_name,
        text = excluded.text,
        content_type = excluded.content_type,
        reply_to_message_id = excluded.reply_to_message_id,
        thread_id = excluded.thread_id,
        source = 'bot',
        source_file = null
    where public.messages.edited_utc is null
       or (excluded.edited_utc is not null
           and excluded.edited_utc >= public.messages.edited_utc);
    return true;
end;
$$;

create or replace function public.insights_status(p_allowed_ids bigint[])
returns table (
    chat_id bigint,
    title text,
    membership text,
    stored_messages bigint,
    bot_messages bigint,
    export_messages bigint,
    first_message_utc timestamptz,
    last_message_utc timestamptz
)
language sql
stable
security invoker
set search_path = ''
as $$
    select c.chat_id, c.title, c.membership,
           count(m.message_id),
           count(m.message_id) filter (where m.source = 'bot'),
           count(m.message_id) filter (where m.source = 'export'),
           min(m.sent_utc), max(m.sent_utc)
    from public.chats c
    left join public.messages m using (chat_id)
    where c.chat_id = any(p_allowed_ids)
    group by c.chat_id, c.title, c.membership
    order by c.title;
$$;

create or replace function public.insights_messages(
    p_allowed_ids bigint[],
    p_since timestamptz,
    p_limit integer,
    p_group bigint,
    p_query text
)
returns table (
    chat_id bigint,
    group_title text,
    message_id bigint,
    sent_utc timestamptz,
    edited_utc timestamptz,
    author_name text,
    text text,
    content_type text,
    reply_to_message_id bigint,
    thread_id bigint,
    source text
)
language sql
stable
security invoker
set search_path = ''
as $$
    select m.chat_id, c.title, m.message_id, m.sent_utc, m.edited_utc,
           m.author_name, m.text, m.content_type, m.reply_to_message_id,
           m.thread_id, m.source
    from public.messages m
    join public.chats c using (chat_id)
    where m.chat_id = any(p_allowed_ids)
      and m.sent_utc >= p_since
      and (p_group is null or m.chat_id = p_group)
      and (p_query is null or position(lower(p_query) in lower(coalesce(m.text, ''))) > 0)
    order by m.sent_utc desc, m.message_id desc
    limit least(greatest(p_limit, 1), 500);
$$;

create or replace function public.insights_claim_scheduled_actions(
    p_allowed_ids bigint[],
    p_limit integer
) returns setof public.scheduled_actions
language plpgsql
security invoker
set search_path = ''
as $$
begin
    return query
    with picked as (
        select a.id
        from public.scheduled_actions a
        where a.chat_id = any(p_allowed_ids)
          and a.scheduled_for <= now()
          and (
              a.status = 'pending'
              or (a.status = 'processing' and a.updated_at < now() - interval '15 minutes')
          )
        order by a.scheduled_for, a.id
        limit least(greatest(p_limit, 1), 25)
        for update skip locked
    )
    update public.scheduled_actions a
       set status = 'processing',
           attempts = a.attempts + 1,
           updated_at = now(),
           last_error = null
      from picked
     where a.id = picked.id
    returning a.*;
end;
$$;

create or replace function public.insights_finish_scheduled_action(
    p_id bigint,
    p_success boolean,
    p_telegram_message_id bigint,
    p_error text
) returns boolean
language plpgsql
security invoker
set search_path = ''
as $$
declare
    v_rows integer;
begin
    update public.scheduled_actions a
       set status = case
               when p_success and a.repeat_interval_minutes is not null then 'pending'
               when p_success then 'sent'
               when a.attempts >= 5 then 'failed'
               else 'pending'
           end,
           scheduled_for = case
               when p_success and a.repeat_interval_minutes is not null
                   then now() + make_interval(mins => a.repeat_interval_minutes)
               when not p_success and a.attempts < 5
                   then now() + interval '5 minutes'
               else a.scheduled_for
           end,
           telegram_message_id = case when p_success then p_telegram_message_id else a.telegram_message_id end,
           last_error = case when p_success then null else left(coalesce(p_error, 'delivery failed'), 500) end,
           sent_at = case when p_success then now() else a.sent_at end,
           updated_at = now()
     where a.id = p_id
       and a.status = 'processing';
    get diagnostics v_rows = row_count;
    return v_rows > 0;
end;
$$;

create or replace function public.insights_register_daily_poll(
    p_poll_id text,
    p_chat_id bigint,
    p_thread_id bigint,
    p_work_date date,
    p_telegram_message_id bigint
) returns boolean
language plpgsql
security invoker
set search_path = ''
as $$
begin
    insert into public.daily_polls(poll_id, chat_id, thread_id, work_date, telegram_message_id)
    values (p_poll_id, p_chat_id, p_thread_id, p_work_date, p_telegram_message_id)
    on conflict (chat_id, work_date) do nothing;
    return true;
end;
$$;

create or replace function public.insights_ingest_poll_answer(
    p_update jsonb,
    p_allowed_ids bigint[]
) returns boolean
language plpgsql
security invoker
set search_path = ''
as $$
declare
    v_answer jsonb := p_update->'poll_answer';
    v_poll_id text;
    v_chat_id bigint;
    v_user jsonb;
    v_user_id bigint;
    v_user_name text;
    v_active boolean;
begin
    if v_answer is null then
        return false;
    end if;
    v_poll_id := v_answer->>'poll_id';
    select p.chat_id into v_chat_id
      from public.daily_polls p
     where p.poll_id = v_poll_id;
    if v_chat_id is null or not (v_chat_id = any(p_allowed_ids)) then
        return false;
    end if;
    v_user := v_answer->'user';
    v_user_id := (v_user->>'id')::bigint;
    if v_user_id is null then
        return false;
    end if;
    v_user_name := nullif(trim(concat_ws(' ', v_user->>'first_name', v_user->>'last_name')), '');
    v_user_name := coalesce(v_user_name, v_user->>'username', v_user_id::text);
    select exists (
        select 1
          from jsonb_array_elements_text(coalesce(v_answer->'option_ids', '[]'::jsonb)) as choices(value)
         where value::integer = 0
    ) into v_active;
    insert into public.daily_poll_answers(poll_id, user_id, user_name, active, updated_at)
    values (v_poll_id, v_user_id, v_user_name, v_active, now())
    on conflict (poll_id, user_id) do update set
        user_name = excluded.user_name,
        active = excluded.active,
        updated_at = excluded.updated_at;
    return true;
end;
$$;

create or replace function public.insights_daily_poll_counts(
    p_work_date date,
    p_allowed_ids bigint[]
) returns table (
    chat_id bigint,
    poll_id text,
    active_workers bigint,
    total_responses bigint
)
language sql
stable
security invoker
set search_path = ''
as $$
    select p.chat_id, p.poll_id,
           count(a.user_id) filter (where a.active),
           count(a.user_id)
      from public.daily_polls p
      left join public.daily_poll_answers a using (poll_id)
     where p.work_date = p_work_date
       and p.chat_id = any(p_allowed_ids)
     group by p.chat_id, p.poll_id;
$$;

revoke all on function public.insights_ingest_update(jsonb, bigint[]) from public, anon, authenticated;
revoke all on function public.insights_status(bigint[]) from public, anon, authenticated;
revoke all on function public.insights_messages(bigint[], timestamptz, integer, bigint, text) from public, anon, authenticated;
revoke all on function public.insights_claim_scheduled_actions(bigint[], integer) from public, anon, authenticated;
revoke all on function public.insights_finish_scheduled_action(bigint, boolean, bigint, text) from public, anon, authenticated;
revoke all on function public.insights_register_daily_poll(text, bigint, bigint, date, bigint) from public, anon, authenticated;
revoke all on function public.insights_ingest_poll_answer(jsonb, bigint[]) from public, anon, authenticated;
revoke all on function public.insights_daily_poll_counts(date, bigint[]) from public, anon, authenticated;
grant execute on function public.insights_ingest_update(jsonb, bigint[]) to service_role;
grant execute on function public.insights_status(bigint[]) to service_role;
grant execute on function public.insights_messages(bigint[], timestamptz, integer, bigint, text) to service_role;
grant execute on function public.insights_claim_scheduled_actions(bigint[], integer) to service_role;
grant execute on function public.insights_finish_scheduled_action(bigint, boolean, bigint, text) to service_role;
grant execute on function public.insights_register_daily_poll(text, bigint, bigint, date, bigint) to service_role;
grant execute on function public.insights_ingest_poll_answer(jsonb, bigint[]) to service_role;
grant execute on function public.insights_daily_poll_counts(date, bigint[]) to service_role;

notify pgrst, 'reload schema';
