create table if not exists public.scheduled_actions (
    id bigint generated by default as identity primary key,
    chat_id bigint not null references public.chats(chat_id),
    action_type text not null check (action_type in ('message', 'poll')),
    payload jsonb not null,
    scheduled_for timestamptz not null,
    repeat_interval_minutes integer check (repeat_interval_minutes is null or repeat_interval_minutes > 0),
    status text not null default 'pending' check (status in ('pending', 'processing', 'sent', 'failed', 'cancelled')),
    attempts integer not null default 0,
    telegram_message_id bigint,
    last_error text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    sent_at timestamptz
);

create index if not exists scheduled_actions_due
    on public.scheduled_actions(status, scheduled_for);

alter table public.scheduled_actions enable row level security;
revoke all on public.scheduled_actions from public, anon, authenticated;
grant select, insert, update on public.scheduled_actions to service_role;
grant usage, select on sequence public.scheduled_actions_id_seq to service_role;

create or replace function public.insights_claim_scheduled_actions(
    p_allowed_ids bigint[],
    p_limit integer
) returns setof public.scheduled_actions
language plpgsql
security invoker
set search_path = ''
as $$
begin
    return query
    with picked as (
        select a.id
        from public.scheduled_actions a
        where a.chat_id = any(p_allowed_ids)
          and a.scheduled_for <= now()
          and (
              a.status = 'pending'
              or (a.status = 'processing' and a.updated_at < now() - interval '15 minutes')
          )
        order by a.scheduled_for, a.id
        limit least(greatest(p_limit, 1), 25)
        for update skip locked
    )
    update public.scheduled_actions a
       set status = 'processing',
           attempts = a.attempts + 1,
           updated_at = now(),
           last_error = null
      from picked
     where a.id = picked.id
    returning a.*;
end;
$$;

create or replace function public.insights_finish_scheduled_action(
    p_id bigint,
    p_success boolean,
    p_telegram_message_id bigint,
    p_error text
) returns boolean
language plpgsql
security invoker
set search_path = ''
as $$
declare
    v_rows integer;
begin
    update public.scheduled_actions a
       set status = case
               when p_success and a.repeat_interval_minutes is not null then 'pending'
               when p_success then 'sent'
               when a.attempts >= 5 then 'failed'
               else 'pending'
           end,
           scheduled_for = case
               when p_success and a.repeat_interval_minutes is not null
                   then now() + make_interval(mins => a.repeat_interval_minutes)
               when not p_success and a.attempts < 5
                   then now() + interval '5 minutes'
               else a.scheduled_for
           end,
           telegram_message_id = case when p_success then p_telegram_message_id else a.telegram_message_id end,
           last_error = case when p_success then null else left(coalesce(p_error, 'delivery failed'), 500) end,
           sent_at = case when p_success then now() else a.sent_at end,
           updated_at = now()
     where a.id = p_id
       and a.status = 'processing';
    get diagnostics v_rows = row_count;
    return v_rows > 0;
end;
$$;

revoke all on function public.insights_claim_scheduled_actions(bigint[], integer) from public, anon, authenticated;
revoke all on function public.insights_finish_scheduled_action(bigint, boolean, bigint, text) from public, anon, authenticated;
grant execute on function public.insights_claim_scheduled_actions(bigint[], integer) to service_role;
grant execute on function public.insights_finish_scheduled_action(bigint, boolean, bigint, text) to service_role;

notify pgrst, 'reload schema';
